from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from app.cio.bulk_importer import (
    FinecoBulkImporter,
    ImportAction,
)
from app.cio.storage import Stage3Store

from app.cio.models import (
    Direction,
    OpportunityStatus,
    TradeOpportunity,
    TradingHorizon,
)


NOW = datetime(
    2026,
    8,
    17,
    14,
    0,
    0,
    tzinfo=timezone.utc,
)


def _write_import_file(
    path: Path,
    *,
    description: str = "Super Micro Computer Ordinary",
    broker_leverage: float | None = 1,
) -> None:
    """
    Create one valid Fineco bulk import JSON file.

    The instrument represents SMCI Ordinary on NASDAQ.
    """

    payload = {
        "schema_version": "1.0",
        "batch_name": "Fineco SMCI test",
        "created_at": NOW.isoformat(),
        "notes": "Generated by pytest",
        "instruments": [
            {
                "payload": {
                    "underlying": "SMCI",
                    "reference_underlying": "SMCI",
                    "exposure_relationship": "DIRECT",

                    "description": description,

                    "instrument_type": "ORDINARY",
                    "trading_mode": "ORDINARY",

                    "fineco_symbol": "SMCI.O",
                    "market": "NASDAQ",

                    "quote_currency": "USD",
                    "settlement_currency": "USD",
                    "margin_currency": None,

                    "long_available": True,
                    "short_available": True,

                    "intraday_available": True,
                    "overnight_available": True,

                    "broker_leverage": broker_leverage,
                    "embedded_leverage": 1,

                    "margin_pct": None,

                    "tick_size": 0.01,
                    "tick_currency": "USD",

                    "commission": None,
                    "overnight_financing_pct": None,

                    "certificate_terms": None,
                    "market_snapshot": None,

                    "notes": "Fineco SMCI Ordinary test",
                }
            }
        ],
    }

    path.write_text(
        json.dumps(
            payload,
            indent=2,
        ),
        encoding="utf-8",
    )


# =============================================================
# NEW
# =============================================================


def test_bulk_import_new_instrument(
    tmp_path,
):
    db = tmp_path / "stage3.db"
    import_file = (
        tmp_path
        / "fineco_smci.json"
    )

    _write_import_file(
        import_file
    )

    store = Stage3Store(
        db
    )

    importer = FinecoBulkImporter(
        store
    )

    result = importer.import_file(
        import_file
    )

    assert result.new_count == 1
    assert result.update_count == 0
    assert result.unchanged_count == 0
    assert result.error_count == 0

    assert len(
        result.items
    ) == 1

    assert (
        result.items[0].action
        == ImportAction.NEW
    )

    instruments = (
        store.find_fineco_instruments(
            "SMCI"
        )
    )

    assert len(
        instruments
    ) == 1

    instrument = (
        instruments[0]
    )

    assert (
        instrument.underlying
        == "SMCI"
    )

    assert (
        instrument.fineco_symbol
        == "SMCI.O"
    )

    assert (
        instrument.broker_leverage
        == 1
    )

    assert (
        instrument.embedded_leverage
        == 1
    )


# =============================================================
# IDEMPOTENCY / UNCHANGED
# =============================================================


def test_bulk_import_same_file_is_unchanged(
    tmp_path,
):
    db = tmp_path / "stage3.db"
    import_file = (
        tmp_path
        / "fineco_smci.json"
    )

    _write_import_file(
        import_file
    )

    store = Stage3Store(
        db
    )

    importer = FinecoBulkImporter(
        store
    )

    first = importer.import_file(
        import_file
    )

    second = importer.import_file(
        import_file
    )

    assert first.new_count == 1

    assert (
        second.new_count
        == 0
    )

    assert (
        second.update_count
        == 0
    )

    assert (
        second.unchanged_count
        == 1
    )

    assert (
        second.error_count
        == 0
    )

    instruments = (
        store.find_fineco_instruments(
            "SMCI"
        )
    )

    # The second import must NOT create
    # another FinecoInstrument.
    assert len(
        instruments
    ) == 1


# =============================================================
# UPDATE
# =============================================================


def test_bulk_import_updates_existing_instrument(
    tmp_path,
):
    db = tmp_path / "stage3.db"

    original_file = (
        tmp_path
        / "smci_original.json"
    )

    updated_file = (
        tmp_path
        / "smci_updated.json"
    )

    _write_import_file(
        original_file,
        description=(
            "Super Micro Computer Ordinary"
        ),
    )

    _write_import_file(
        updated_file,
        description=(
            "Super Micro Computer "
            "Ordinary NASDAQ"
        ),
    )

    store = Stage3Store(
        db
    )

    importer = FinecoBulkImporter(
        store
    )

    first = importer.import_file(
        original_file
    )

    assert (
        first.new_count
        == 1
    )

    before = (
        store.find_fineco_instruments(
            "SMCI"
        )[0]
    )

    original_id = (
        before.instrument_id
    )

    second = importer.import_file(
        updated_file
    )

    assert (
        second.new_count
        == 0
    )

    assert (
        second.update_count
        == 1
    )

    assert (
        second.unchanged_count
        == 0
    )

    assert (
        second.error_count
        == 0
    )

    after = (
        store.find_fineco_instruments(
            "SMCI"
        )[0]
    )

    # Update must preserve stable identity.
    assert (
        after.instrument_id
        == original_id
    )

    assert (
        after.description
        == (
            "Super Micro Computer "
            "Ordinary NASDAQ"
        )
    )


# =============================================================
# DRY RUN
# =============================================================


def test_bulk_import_dry_run_does_not_write_database(
    tmp_path,
):
    db = tmp_path / "stage3.db"

    import_file = (
        tmp_path
        / "fineco_smci.json"
    )

    _write_import_file(
        import_file
    )

    store = Stage3Store(
        db
    )

    importer = FinecoBulkImporter(
        store
    )

    result = importer.import_file(
        import_file,
        dry_run=True,
    )

    assert result.dry_run is True

    assert (
        result.new_count
        == 1
    )

    assert (
        result.error_count
        == 0
    )

    instruments = (
        store.find_fineco_instruments(
            "SMCI"
        )
    )

    assert instruments == []


# =============================================================
# INVALID INSTRUMENT
# =============================================================


def test_bulk_import_invalid_instrument_returns_error(
    tmp_path,
):
    db = tmp_path / "stage3.db"

    import_file = (
        tmp_path
        / "invalid.json"
    )

    payload = {
        "schema_version": "1.0",
        "batch_name": "Invalid Fineco test",
        "created_at": NOW.isoformat(),
        "instruments": [
            {
                "payload": {
                    # underlying deliberately missing

                    "reference_underlying": "SMCI",
                    "exposure_relationship": "DIRECT",

                    "description": "Broken instrument",

                    "instrument_type": "ORDINARY",
                    "trading_mode": "ORDINARY",

                    "fineco_symbol": "SMCI.O",
                    "market": "NASDAQ",

                    "quote_currency": "USD",

                    "broker_leverage": 1,
                    "embedded_leverage": 1,
                }
            }
        ],
    }

    import_file.write_text(
        json.dumps(
            payload,
            indent=2,
        ),
        encoding="utf-8",
    )

    store = Stage3Store(
        db
    )

    importer = FinecoBulkImporter(
        store
    )

    result = importer.import_file(
        import_file
    )

    assert (
        result.new_count
        == 0
    )

    assert (
        result.update_count
        == 0
    )

    assert (
        result.unchanged_count
        == 0
    )

    assert (
        result.error_count
        == 1
    )

    assert (
        result.items[0].action
        == ImportAction.ERROR
    )

    assert (
        result.items[0].message
        is not None
    )


# =============================================================
# MULTIPLE INSTRUMENTS
# =============================================================


def test_bulk_import_multiple_instruments(
    tmp_path,
):
    db = tmp_path / "stage3.db"

    import_file = (
        tmp_path
        / "fineco_smci_multi.json"
    )

    payload = {
        "schema_version": "1.0",
        "batch_name": "Fineco SMCI multi",
        "created_at": NOW.isoformat(),
        "instruments": [
            {
                "payload": {
                    "underlying": "SMCI",
                    "reference_underlying": "SMCI",
                    "exposure_relationship": "DIRECT",

                    "description": (
                        "Super Micro Ordinary"
                    ),

                    "instrument_type": "ORDINARY",
                    "trading_mode": "ORDINARY",

                    "fineco_symbol": "SMCI.O",
                    "market": "NASDAQ",

                    "quote_currency": "USD",
                    "settlement_currency": "USD",

                    "long_available": True,
                    "short_available": True,

                    "intraday_available": True,
                    "overnight_available": True,

                    "broker_leverage": 1,
                    "embedded_leverage": 1,

                    "tick_size": 0.01,
                    "tick_currency": "USD",
                }
            },
            {
                "payload": {
                    "underlying": "SMCI",
                    "reference_underlying": "SMCI",
                    "exposure_relationship": "DIRECT",

                    "description": (
                        "Super Micro Margin X2.9 "
                        "Overnight"
                    ),

                    "instrument_type": "MARGIN",
                    "trading_mode": "OVERNIGHT",

                    "fineco_symbol": "SMCI.O",
                    "market": "NASDAQ",

                    "quote_currency": "USD",
                    "settlement_currency": "USD",
                    "margin_currency": "USD",

                    "long_available": True,
                    "short_available": True,

                    "intraday_available": False,
                    "overnight_available": True,

                    "broker_leverage": 2.9,
                    "embedded_leverage": 1,

                    "margin_pct": None,

                    "tick_size": 0.01,
                    "tick_currency": "USD",
                }
            },
            {
                "payload": {
                    "underlying": "SMCI",
                    "reference_underlying": "SMCI",
                    "exposure_relationship": "DIRECT",

                    "description": (
                        "Super Micro CFDC X5"
                    ),

                    "instrument_type": "CFDC",
                    "trading_mode": "OVERNIGHT",

                    "fineco_symbol": (
                        "SMCICFD.CFD"
                    ),
                    "market": "CFDC",

                    "quote_currency": "USD",
                    "settlement_currency": "EUR",
                    "margin_currency": "EUR",

                    "long_available": True,
                    "short_available": True,

                    "intraday_available": False,
                    "overnight_available": True,

                    "broker_leverage": 5,
                    "embedded_leverage": 1,

                    "margin_pct": 20,

                    "tick_size": 0.01,
                    "tick_currency": "USD",
                }
            },
        ],
    }

    import_file.write_text(
        json.dumps(
            payload,
            indent=2,
        ),
        encoding="utf-8",
    )

    store = Stage3Store(
        db
    )

    importer = FinecoBulkImporter(
        store
    )

    result = importer.import_file(
        import_file
    )

    assert (
        result.new_count
        == 3
    )

    assert (
        result.error_count
        == 0
    )

    instruments = (
        store.find_fineco_instruments(
            "SMCI"
        )
    )

    assert len(
        instruments
    ) == 3

    leverages = sorted(
        item.broker_leverage
        for item in instruments
        if item.broker_leverage
        is not None
    )

    assert leverages == [
        1,
        2.9,
        5,
    ]
def _make_waiting_opportunity(
    *,
    opportunity_id: str,
    ticker: str,
) -> TradeOpportunity:

    now = datetime(
        2026,
        8,
        18,
        8,
        0,
        0,
        tzinfo=timezone.utc,
    )

    return TradeOpportunity(
        opportunity_id=opportunity_id,
        snapshot_id="SNAP-BULK-TEST",
        created_at=now,
        updated_at=now,

        ticker=ticker,

        direction=Direction.LONG,

        horizon=TradingHorizon.SWING,

        expected_holding_min_days=5,
        expected_holding_max_days=15,

        confidence=0.80,

        target_exposure_eur=5000,
        max_intended_loss_eur=500,

        thesis=(
            "Bulk importer integration test"
        ),

        catalyst=None,

        key_risks=[],
        evidence_ids=[],

        status=(
            OpportunityStatus
            .WAITING_FOR_BROKER_INSTRUMENTS
        ),

        broker_instruments_required=True,

        broker_instruments_available=False,

        broker_instrument_count=0,

        rejection_reason=None,
        expiry_reason=None,

        notes="pytest",
    )

def test_bulk_import_refreshes_waiting_opportunity(
    tmp_path,
):
    db = tmp_path / "stage3.db"

    import_file = (
        tmp_path
        / "fineco_smci.json"
    )

    _write_import_file(
        import_file
    )

    store = Stage3Store(
        db
    )

    opportunity = (
        _make_waiting_opportunity(
            opportunity_id=(
                "OPP-SMCI-WAITING"
            ),
            ticker="SMCI",
        )
    )

    store.save_trade_opportunity(
        opportunity
    )

    before = (
        store.get_trade_opportunity(
            opportunity.opportunity_id
        )
    )

    assert before is not None

    assert (
        before.status
        == OpportunityStatus
        .WAITING_FOR_BROKER_INSTRUMENTS
    )

    importer = FinecoBulkImporter(
        store
    )

    result = importer.import_file(
        import_file
    )

    assert (
        result.error_count
        == 0
    )

    assert (
        result.new_count
        == 1
    )

    assert (
        result.refreshed_opportunity_count
        == 1
    )

    assert (
        result.refreshed_opportunity_ids
        == [
            "OPP-SMCI-WAITING"
        ]
    )

    after = (
        store.get_trade_opportunity(
            opportunity.opportunity_id
        )
    )

    assert after is not None

    assert (
        after.status
        == OpportunityStatus
        .READY_FOR_INSTRUMENT_SELECTION
    )

    assert (
        after.broker_instruments_available
        is True
    )

    assert (
        after.broker_instrument_count
        == 1
    )

def test_bulk_import_dry_run_does_not_refresh_opportunity(
    tmp_path,
):
    db = tmp_path / "stage3.db"

    import_file = (
        tmp_path
        / "fineco_smci.json"
    )

    _write_import_file(
        import_file
    )

    store = Stage3Store(
        db
    )

    opportunity = (
        _make_waiting_opportunity(
            opportunity_id=(
                "OPP-SMCI-DRYRUN"
            ),
            ticker="SMCI",
        )
    )

    store.save_trade_opportunity(
        opportunity
    )

    importer = FinecoBulkImporter(
        store
    )

    result = importer.import_file(
        import_file,
        dry_run=True,
    )

    assert (
        result.refreshed_opportunity_count
        == 0
    )

    assert (
        result.refreshed_opportunity_ids
        == []
    )

    after = (
        store.get_trade_opportunity(
            opportunity.opportunity_id
        )
    )

    assert after is not None

    assert (
        after.status
        == OpportunityStatus
        .WAITING_FOR_BROKER_INSTRUMENTS
    )

    assert (
        after.broker_instruments_available
        is False
    )

    assert (
        after.broker_instrument_count
        == 0
    )

    # Dry-run also must not have inserted
    # the Fineco instrument itself.
    instruments = (
        store.find_fineco_instruments(
            "SMCI"
        )
    )

    assert instruments == []

def test_unchanged_bulk_import_can_refresh_waiting_opportunity(
    tmp_path,
):
    db = tmp_path / "stage3.db"

    import_file = (
        tmp_path
        / "fineco_smci.json"
    )

    _write_import_file(
        import_file
    )

    store = Stage3Store(
        db
    )

    importer = FinecoBulkImporter(
        store
    )

    # First import populates the Fineco cache.
    first = importer.import_file(
        import_file
    )

    assert first.new_count == 1

    # Opportunity is created AFTER the Fineco cache
    # already contains the instrument.
    opportunity = (
        _make_waiting_opportunity(
            opportunity_id=(
                "OPP-SMCI-UNCHANGED"
            ),
            ticker="SMCI",
        )
    )

    store.save_trade_opportunity(
        opportunity
    )

    # Re-importing the same broker file should be
    # UNCHANGED, but must still refresh the opportunity.
    second = importer.import_file(
        import_file
    )

    assert (
        second.new_count
        == 0
    )

    assert (
        second.unchanged_count
        == 1
    )

    assert (
        second.refreshed_opportunity_count
        == 1
    )

    after = (
        store.get_trade_opportunity(
            opportunity.opportunity_id
        )
    )

    assert after is not None

    assert (
        after.status
        == OpportunityStatus
        .READY_FOR_INSTRUMENT_SELECTION
    )
